version: "3.9"
services:
  bechtle-web:
    build: ./bechtle-web
    ports:
      - "8080:80"
    volumes: 
     - /root/data:/usr/share/nginx/html
    depends_on: 
      - bechtle-job
  bechtle-job:
    build: ./bechtle-job
    volumes: 
      - /root/data:/data
